# Generated by Django 5.0 on 2024-01-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(allow_unicode=True, editable=False, null=True, unique=True),
        ),
    ]
