# Generated by Django 5.0 on 2024-01-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=0, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
