# Generated by Django 5.0 on 2024-01-16 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_companyinfo_foundation_year'),
        ('jobs', '0003_alter_job_slug'),
        ('locations', '0002_alter_city_state_alter_state_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='locations.city'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.company'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='industry',
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='accounts.industry'),
            preserve_default=False,
        ),
    ]
