# Generated by Django 5.0 on 2024-01-24 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_companyinfo_foundation_year'),
        ('jobs', '0004_alter_job_city_alter_job_company_remove_job_industry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='job',
            name='savers',
            field=models.ManyToManyField(related_name='saved_jobs', through='jobs.UserSavedJobs', to='accounts.user'),
        ),
        migrations.AddConstraint(
            model_name='usersavedjobs',
            constraint=models.UniqueConstraint(fields=('job', 'user'), name='no_repeated_saved_jobs_for_users'),
        ),
    ]
