# Generated by Django 5.0 on 2024-01-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_jobapplication_questions_alter_job_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cv',
            field=models.FileField(default='cv.pdf', upload_to='applications_cvs'),
            preserve_default=False,
        ),
    ]
