# Generated by Django 5.0 on 2024-01-12 16:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_companyinfo_industry_companyinfo_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='foundation_year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
